# spring:
#   application:
#     name: scs-kafka-sandbox
#   cloud:
#     function:
#       definition:
#         function
#     stream:
#       bindings:
#         consumer-in-0:
#           destination: input-topic
#           group: some-group
#         function-in-0:
#           destination: input-topic
#           group: some-group
# ---

spring:
  application:
    name: scs-kafka-sandbox
  cloud:
    function:
      definition:
        function
    stream:
      bindings:
        consumer-in-0:
          destination: input-topic
          group: some-group
        function-in-0:
          destination: input-topic
          group: some-group
      kafka:
        binder:
          consumerProperties:
            "group.instance.id": "123"



          
