spring:
  application:
    name: scs-kafka-sandbox
  cloud:
    function:
      definition:
        consumer
    stream:
      bindings:
        consumer-in-0:
          destination: input-topic1,input-topic2
          group: some-group
