spring:
  application:
    name: scs-kafka-sandbox
  cloud:
    function:
      definition:
        consumer
    stream:
      # default:
      #   producer:
      #     useNativeEncoding: true
      bindings:
        consumer-in-0:
          destination: input-topic
          group: some-group
        # cmProducer-out-0:
        #   cmProducer:
        #     useNativeEncoding: true
      kafka:
        binder:
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "auto.offset.reset": "earliest"
            "group.instance.id": "1"
            "spring.json.trusted.packages": "jayslabs.kafka.section11.dto"