

# Section 6: Content-Based Message Routing without StreamBridge, but via Message Header
spring:
  # application:
  #   name: scs-kafka-sandbox
  cloud:
    function:
      definition: orderEventProducer;orderProcessor;digitalDlvryCnsmr;physicalDlvryCnsmr
    stream:
      bindings:
        # Producer binding
        orderEventProducer-out-0:
          destination: order-events-topic
        
        # Processor input binding  
        orderProcessor-in-0:
          destination: order-events-topic
          group: order-processor-group
          
        digital-delivery-out:
          destination: digital-delivery-topic
        physical-delivery-out:
          destination: physical-delivery-topic

        # Consumer bindings (StreamBridge destinations)
        digitalDlvryCnsmr-in-0:
          destination: digital-delivery-topic
          group: digital-delivery-group
          
        physicalDlvryCnsmr-in-0:
          destination: physical-delivery-topic
          group: physical-delivery-group
      kafka:
        binder:
          producer-properties:
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"