# --- with producer
spring:
  application:
    name: scs-kafka-sandbox
  cloud:
    function:
      definition:
        producer;consumer
    stream:
      bindings:
        producer-out-0:
          destination: input-topic
        consumer-in-0:
          destination: input-topic
          group: some-group
      kafka:
        binder:
          producer-properties:
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "group.instance.id": "1"
