spring:
  application:
    name: scs-kafka-sandbox
  cloud:
    function:
      definition:
        consumer
    stream:
      bindings:
        cmConsumer-in-0:
          destination: input-topic
          group: some-group
      # kafka:
      #   binder:
      #     consumer-properties:
      #       "key.deserializer": org.apache.kafka.common.serialization.IntegerDeserializer
      #       "value.deserializer": org.apache.kafka.common.serialization.IntegerDeserializer
      #       "auto.offset.reset": "earliest"
      #       "group.instance.id": "1"